version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn
  pre_build:
    commands:
      - git config --global user.email "petersonvgama@gmail.com"
      - git config --global user.name "Serenity - CodeBuild"
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - yarn version --patch
artifacts:
  files:
    - bin/**/*
  name: authenticator/`yarn --silent current-version`
